description_path: description
dest_path: /home/gheorghe/Desktop/s_AI/s_AI/target_dataset
man_path: man
row_path: row
input_suffix: .png
target_path: targets
input_path: inputs
output_suffix: .csv
source_path: /home/gheorghe/Desktop/s_AI/s_AI/gen_data/8K